# .kitchen.yml

---
driver:
  name: docker


platforms:
  - name: centos-7.0

suites:
  - name: source
    run_list:
      - recipe[apm::version]
    attributes:
      vim:
        install_method: "source"
  - name: package
    run_list:
      - recipe[apm::version]
    attributes:
      vim:
        install_method: "package"
